#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 11 12:42:18 2020

@author: carolinebarstow
"""

#imports
from tkinter import Tk
from tkinter import *
from tkinter import ttk
from tkinter import font

class CounterClass:
    point = 0
#    root = Tk()

    def __init__(self, app, x, y, item, textX, textY):
        self.item = item
        self.app = app
        self.x = x
        self.y = y
        self.textX = textX
        self.textY = textY
        
        self.textLbl = Label(self.app, text = item).grid(column=textX, row=textY)
       

        self.DisplayLabel = Label(self.app, text = self.point)
        self.DisplayLabel.grid(column = self.x, row = self.y)
        

        self.Plus1Button = Button(self.app, text = "+", command=self.plus1, bg="green4")
        self.Plus1Button.grid(column = (self.x+1), row = y)

        self.Neg1Button = Button(self.app, text = "-", command=self.neg1, bg="red4")
        self.Neg1Button.grid(column = (self.x-1), row = y)

#        self.root.mainloop()
    
        
   
    def plus1(self):
        self.point += 1
        self.DisplayLabel["text"]=str(self.point)

        
    def neg1(self):
        if self.point  > 0:
            self.point -= 1
            self.DisplayLabel["text"]=str(self.point)


class lowGoalCounterClass:
    shotsMade = 0
    shotsTaken = 0

    def __init__(self, app, x, y, item, textX, textY):
        self.item = item
        self.app = app
        self.x = x
        self.y = y
        self.textX = textX
        self.textY = textY
        
        self.textLbl = Label(self.app, text = item).grid(column=textX, row=textY)
       

        self.madeDisplayLabel = Label(self.app, text = self.shotsMade)
        self.madeDisplayLabel.grid(column = (self.x+5), row = self.y)
        

        self.Plus1Button = Button(self.app, text = "+", command=self.madePlus1, bg="green4")
        self.Plus1Button.grid(column = (self.x+6), row = y)

        self.Neg1Button = Button(self.app, text = "-", command=self.madeNeg1, bg="red4")
        self.Neg1Button.grid(column = (self.x+4), row = y)

        self.Plus5Button = Button(self.app, text = "+", command=self.madePlus5, bg="green4")
        self.Plus5Button.grid(column = (self.x+7), row = y)

        self.Neg5Button = Button(self.app, text = "-", command=self.madeNeg5, bg="red4")
        self.Neg5Button.grid(column = (self.x+3), row = y)

        self.takenDisplayLabel = Label(self.app, text = self.shotsTaken)
        self.takenDisplayLabel.grid(column = self.x, row = self.y)
        

        self.takenPlus1Button = Button(self.app, text = "+", command=self.takenPlus1, bg="green4")
        self.takenPlus1Button.grid(column = (self.x+1), row = y)

        self.takenNeg1Button = Button(self.app, text = "-", command=self.takenNeg1, bg="red4")
        self.takenNeg1Button.grid(column = (self.x-1), row = y)

    
        self.takenPlus5Button = Button(self.app, text = "+", command=self.takenPlus5, bg="green4")
        self.takenPlus5Button.grid(column = (self.x+2), row = y, padx=17, sticky='E')

        self.takenNeg5Button = Button(self.app, text = "-", command=self.takenNeg5, bg="red4")
        self.takenNeg5Button.grid(column = (self.x-2), row = y)

#        self.root.mainloop()
    
        
   
    def madePlus5(self):
        self.shotsMade += 5
        self.shotsTaken += 5
        self.madeDisplayLabel["text"]=str(self.shotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def madeNeg5(self):
        if self.shotsMade  >= 5:
            self.shotsMade -= 5
            self.shotsTaken -=5
            self.madeDisplayLabel["text"]=str(self.shotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
        else:
            self.shotsMade = 0
            self.shotsTaken = 0
            self.madeDisplayLabel["text"]=str(self.shotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
            
    def takenPlus5(self):
#        self.shotsMade += 5
        self.shotsTaken += 5
#        self.madeDisplayLabel["text"]=str(self.shotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def takenNeg5(self):
        if self.shotsTaken  >= self.shotsMade+5:
#            self.shotsMade -= 5
            self.shotsTaken -=5
#            self.madeDisplayLabel["text"]=str(self.shotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
        else:
           self.shotsTaken = self.shotsMade
           self.takenDisplayLabel["text"]=str(self.shotsTaken)
    
    def madePlus1(self):
        self.shotsMade += 1
        self.shotsTaken += 1
        self.madeDisplayLabel["text"]=str(self.shotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def madeNeg1(self):
        if self.shotsMade  > 0:
            self.shotsMade -= 1
            self.shotsTaken -=1
            self.madeDisplayLabel["text"]=str(self.shotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
            
    def takenPlus1(self):
#        self.shotsMade += 1
        self.shotsTaken += 1
#        self.madeDisplayLabel["text"]=str(self.shotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def takenNeg1(self):
        if self.shotsTaken  > self.shotsMade:
#            self.shotsMade -= 1
            self.shotsTaken -=1
#            self.madeDisplayLabel["text"]=str(self.shotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)


class highGoalCounterClass:
    innerShotsMade = 0
    outerShotsMade = 0
    shotsTaken = 0

    def __init__(self, app, x, y, item, textX, textY):
        self.item = item
        self.app = app
        self.x = x
        self.y = y
        self.textX = textX
        self.textY = textY
        
        self.textLbl = Label(self.app, text = item).grid(column=textX, row=textY)
       
#inner made
        self.innerMadeDisplayLabel = Label(self.app, text = self.innerShotsMade)
        self.innerMadeDisplayLabel.grid(column = (self.x+5), row = self.y)

        self.innerPlus1Button = Button(self.app, text = "+", command=self.innerMadePlus1, bg="green4")
        self.innerPlus1Button.grid(column = (self.x+6), row = y)

        self.innerNeg1Button = Button(self.app, text = "-", command=self.innerMadeNeg1, bg="red4")
        self.innerNeg1Button.grid(column = (self.x+4), row = y)

        self.innerPlus5Button = Button(self.app, text = "+", command=self.innerMadePlus5, bg="green4")
        self.innerPlus5Button.grid(column = (self.x+7), row = y)

        self.innerNeg5Button = Button(self.app, text = "-", command=self.innerMadeNeg5, bg="red4")
        self.innerNeg5Button.grid(column = (self.x+3), row = y)

#outer made
        self.outerMadeDisplayLabel = Label(self.app, text = self.outerShotsMade)
        self.outerMadeDisplayLabel.grid(column = (self.x+5), row = self.y+1)        

        self.outerPlus1Button = Button(self.app, text = "+", command=self.outerMadePlus1, bg="green4")
        self.outerPlus1Button.grid(column = (self.x+6), row = y+1)

        self.outerNeg1Button = Button(self.app, text = "-", command=self.outerMadeNeg1, bg="red4")
        self.outerNeg1Button.grid(column = (self.x+4), row = y+1)

        self.outerPlus5Button = Button(self.app, text = "+", command=self.outerMadePlus5, bg="green4")
        self.outerPlus5Button.grid(column = (self.x+7), row = y+1)

        self.outerNeg5Button = Button(self.app, text = "-", command=self.outerMadeNeg5, bg="red4")
        self.outerNeg5Button.grid(column = (self.x+3), row = y+1)

#taken
        self.takenDisplayLabel = Label(self.app, text = self.shotsTaken)
        self.takenDisplayLabel.grid(column = self.x, row = self.y)
        
        self.takenPlus1Button = Button(self.app, text = "+", command=self.takenPlus1, bg="green4")
        self.takenPlus1Button.grid(column = (self.x+1), row = y)

        self.takenNeg1Button = Button(self.app, text = "-", command=self.takenNeg1, bg="red4")
        self.takenNeg1Button.grid(column = (self.x-1), row = y)

    
        self.takenPlus5Button = Button(self.app, text = "+", command=self.takenPlus5, bg="green4")
        self.takenPlus5Button.grid(column = (self.x+2), row = y, padx=17, sticky='E')

        self.takenNeg5Button = Button(self.app, text = "-", command=self.takenNeg5, bg="red4")
        self.takenNeg5Button.grid(column = (self.x-2), row = y)

#        self.root.mainloop()
    
        
#inner made def   
    def innerMadePlus5(self):
        self.innerShotsMade += 5
        self.shotsTaken += 5
        self.innerMadeDisplayLabel["text"]=str(self.innerShotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def innerMadeNeg5(self):
        if self.innerShotsMade  >= 5:
            self.innerShotsMade -= 5
            self.shotsTaken -=5
            self.innerMadeDisplayLabel["text"]=str(self.innerShotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
        else:
            self.innerShotsMade = 0
            self.shotsTaken = 0
            self.madeDisplayLabel["text"]=str(self.innerShotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
            

    def innerMadePlus1(self):
        self.innerShotsMade += 1
        self.shotsTaken += 1
        self.innerMadeDisplayLabel["text"]=str(self.innerShotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def innerMadeNeg1(self):
        if self.innerShotsMade  > 0:
            self.innerShotsMade -= 1
            self.shotsTaken -=1
            self.innerMadeDisplayLabel["text"]=str(self.innerShotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)

#outer made def
    def outerMadePlus5(self):
        self.outerShotsMade += 5
        self.shotsTaken += 5
        self.outerMadeDisplayLabel["text"]=str(self.outerShotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def outerMadeNeg5(self):
        if self.outerShotsMade  >= 5:
            self.outerShotsMade -= 5
            self.shotsTaken -=5
            self.outerMadeDisplayLabel["text"]=str(self.outerShotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
        else:
            self.outerShotsMade = 0
            self.shotsTaken = 0
            self.madeDisplayLabel["text"]=str(self.outerShotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
            

    def outerMadePlus1(self):
        self.outerShotsMade += 1
        self.shotsTaken += 1
        self.outerMadeDisplayLabel["text"]=str(self.outerShotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def outerMadeNeg1(self):
        if self.outerShotsMade  > 0:
            self.outerShotsMade -= 1
            self.shotsTaken -=1
            self.outerMadeDisplayLabel["text"]=str(self.outerShotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)


#taken def
    def takenPlus5(self):
#        self.shotsMade += 5
        self.shotsTaken += 5
#        self.madeDisplayLabel["text"]=str(self.shotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def takenNeg5(self):
        if self.shotsTaken  >= self.outerShotsMade + self.innerShotsMade +5:
#            self.shotsMade -= 5
            self.shotsTaken -=5
#            self.madeDisplayLabel["text"]=str(self.shotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)
        else:
           self.shotsTaken = self.innerShotsMade + self.outerShotsMade
           self.takenDisplayLabel["text"]=str(self.shotsTaken)
                
    def takenPlus1(self):
#        self.shotsMade += 1
        self.shotsTaken += 1
#        self.madeDisplayLabel["text"]=str(self.shotsMade)
        self.takenDisplayLabel["text"]=str(self.shotsTaken)
        
    def takenNeg1(self):
        if self.shotsTaken  > self.innerShotsMade + self.outerShotsMade:
#            self.shotsMade -= 1
            self.shotsTaken -=1
#            self.madeDisplayLabel["text"]=str(self.shotsMade)
            self.takenDisplayLabel["text"]=str(self.shotsTaken)

def sendToDatabase():
    pass

def screenClear():
    pass

#opening tkinter
window = Tk() 
window.geometry('800x480')

window.title('scouting app 2020')

#Give it some style
style = ttk.Style()
style.theme_settings("default",{"TNotebook.Tab":{"configure":{"padding":[20,20]}}})
labelfont = font.Font(family= "times", size= 20)
window.option_add("*Font", labelfont)
labelfont = ('times', 15)
labelfont2 = ('times', 5)

    #edit the tabs here as needed
tab_control = ttk.Notebook(window)
preMatch = ttk.Frame(tab_control)
auto = ttk.Frame(tab_control)
reference = ttk.Frame(tab_control)
tele = ttk.Frame(tab_control)
endGame = ttk.Frame(tab_control)
postMatch = ttk.Frame(tab_control)
tab_control.add(preMatch, text='Pre-Match')
tab_control.add(auto, text='Auto')
tab_control.add(reference, text='Reference Image')
tab_control.add(tele, text='TeleOp')
tab_control.add(endGame, text='End Game')
tab_control.add(postMatch, text='Post-Match')
tab_control.pack(expand=1, fill='both')

#Prematch Screen
name = ttk.Entry(preMatch, width= 30)
name.bind('<Button-1>')
name.grid(column=1, row=0, columnspan=3)
nameLBL = Label(preMatch, text = 'Name:')
nameLBL.grid(column=0, row=0, ipady=17)

teamnum = ttk.Entry(preMatch, width=10)
teamnum.bind('<Button-1>')
teamnum.grid(column=5, row=0)
teamnumLBL = Label(preMatch, text='  Team# you are with:')
teamnumLBL.grid(row=0, column=4)

startPos = IntVar()
aLocation = Radiobutton(preMatch, text = 'A', value = 1, var=startPos)
aLocation.grid(row=1, column=0)
bLocation = Radiobutton(preMatch, text='B', value = 2, var=startPos)
bLocation.grid(row=1, column=1)
cLocation = Radiobutton(preMatch, text = 'C', value = 3, var=startPos)
cLocation.grid(row=1, column=2)
dLocation = Radiobutton(preMatch, text = 'D', value = 4, var=startPos)
dLocation.grid(row=1, column=3)
eLocation = Radiobutton(preMatch, text = 'E', value = 5, var=startPos)
eLocation.grid(row=1, column=4)
fLocation = Radiobutton(preMatch, text = 'F', value = 6, var=startPos)
fLocation.grid(row=1, column=5)
gLocation = Radiobutton(preMatch, text = 'G', value = 7, var=startPos)
gLocation.grid(row=1, column=6, ipadx=14)
hLocation = Radiobutton(preMatch, text = 'H', value = 8, var=startPos)
hLocation.grid(row=1, column=7, ipadx=17)

#auto screen
crossHABLine_State = BooleanVar(False)
crossHABLine = Checkbutton(auto, text='Cross HAB Line', var=crossHABLine_State)
crossHABLine.grid(row=0, column=0, ipady=17)

#TELEOP pagE
            
count1 = CounterClass(tele, 2, 9, 'Foul', 0, 9)
count2 = CounterClass(tele, 2, 10, 'Tech Foul', 0, 10)
bigBoi = lowGoalCounterClass(tele, 3, 2, 'Low', 0, 2)
highAsAKite = highGoalCounterClass(tele, 3, 3, 'High', 0, 3)

rotationalControl = Label(tele, text='Has Rotational Control?')
rotationalControl.grid(column=0, row=6, ipady=23)
startPos = ttk.Combobox(tele)
startPos['values']= ("No", "Yes", "Fail")
startPos.current(0)
startPos.grid(column= 1, row= 6, columnspan= 2)
startPos.config(width= 20)

positionalControl = Label(tele, text='Has Positional Control?')
positionalControl.grid(column=3, row=6, ipady=23)
startPos = ttk.Combobox(tele)
startPos['values']= ("No", "Yes", "Fail")
startPos.current(0)
startPos.grid(column= 4, row= 6, columnspan= 2)
startPos.config(width= 20)

shooterPos = Label(tele, text='Shooter Position')
shooterPos.grid(column=0, row=11, ipady=23)
startPos = ttk.Combobox(tele)
startPos['values']= ("A", "B", "C", "D", "E", "F", "G", "H")
startPos.current(0)
startPos.grid(column= 1, row= 11, columnspan= 2)
startPos.config(width= 20)

defense_State = BooleanVar(False)
defense = Checkbutton(tele, text='Played Defense?', var=defense_State)
defense.grid(row=14, column=0, ipady=17)
window.mainloop()